import {chromium,expect} from '@playwright/test'
import {writeFileSync} from 'node:fs'
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/opt/google/chrome/chrome',headless:true,args:['--no-sandbox']})
const errors=[],checks=[],network=[]
function record(name){checks.push({name,passed:true});console.log('通过',name)}
async function track(context){context.on('page',page=>{page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes(':8100'))network.push({method:r.request().method(),status:r.status(),path:new URL(r.url()).pathname.replace(/\/api\/practice\/[a-f0-9]{64}/,'/api/practice/{本人访问码}')})})})}
async function login(page,id){await page.goto('http://localhost:5173/login');await page.getByLabel('系统用户编号',{exact:true}).fill(id);await page.getByLabel('登录密码').fill('123456');await page.getByRole('button',{name:'登录平台'}).click();await expect(page).toHaveURL('http://localhost:5173/');await expect(page.locator('.toprole')).toBeVisible()}
async function noOverflow(page,name){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();record(name)}
try{
 const tc=await browser.newContext({viewport:{width:1440,height:1000}});await track(tc);const t=await tc.newPage();await login(t,'DEMO_TEACHER');record('教师真实登录')
 await expect(t.getByRole('link',{name:'我的项目数据',exact:true})).toHaveCount(0);await t.goto('http://localhost:5173/data');await expect(t).toHaveURL('http://localhost:5173/');record('教师导航没有业务数据页且路由受限')
 await t.getByRole('link',{name:'班级管理',exact:true}).click();await expect(t.getByRole('cell',{name:'DEMO2026',exact:true})).toBeVisible();await t.screenshot({path:'../docs/screenshots/teacher-classes.png',fullPage:true})
 const demoRow=t.getByRole('row').filter({has:t.getByRole('cell',{name:'DEMO2026',exact:true})});await demoRow.getByRole('button',{name:'编辑',exact:true}).click();await expect(t.getByLabel('班级编号',{exact:true})).toBeDisabled();await t.getByLabel('班级名称',{exact:true}).fill('Vue 实训示范班');await t.getByRole('button',{name:'保存',exact:true}).click();await expect(t.getByRole('dialog')).toHaveCount(0);record('教师班级查询及编辑')
 await t.getByRole('link',{name:'系统用户',exact:true}).click();await expect(t.getByRole('cell',{name:'DEMO2026001',exact:true})).toBeVisible();await t.getByRole('row').filter({has:t.getByRole('cell',{name:'DEMO2026001',exact:true})}).getByRole('button',{name:'编辑',exact:true}).click();await expect(t.getByLabel('系统用户编号（学生为学号）')).toBeDisabled();await t.getByRole('button',{name:'关闭',exact:true}).click();record('系统用户编号不可修改');const imported=t.getByRole('row').filter({has:t.getByRole('cell',{name:'DEMO2026003',exact:true})});if(await imported.count()){await imported.getByRole('button',{name:'删除',exact:true}).click();await t.getByRole('button',{name:'确认执行',exact:true}).click();await expect(t.getByRole('dialog')).toHaveCount(0);record('教师确认后删除隔离导入学生')}
 await t.getByRole('link',{name:'工作空间',exact:true}).click();await t.getByPlaceholder('请输入班级编号').fill('DEMO2026');await t.getByRole('button',{name:'查询',exact:true}).click();await expect(t.getByRole('cell',{name:'DEMO2026001',exact:true})).toBeVisible();record('教师按班级查询真实空间')
 await t.getByRole('link',{name:'学生导入',exact:true}).click();await t.getByLabel('选择学生名单').setInputFiles('../.runtime/fixtures/students.xlsx');await t.getByRole('button',{name:'上传并导入'}).click();await expect(t.getByRole('heading',{name:'导入结果'})).toBeVisible();await expect(t.getByRole('cell',{name:'跳过',exact:true})).toBeVisible();await expect(t.getByRole('cell',{name:'失败',exact:true})).toBeVisible();record('Excel上传及部分失败逐行结果');await t.screenshot({path:'../docs/screenshots/import-result.png',fullPage:true})
 await t.getByRole('link',{name:'接口文档',exact:true}).click();await t.getByRole('button',{name:'校园报修',exact:true}).click();await t.locator('.doc-folder-toggle').first().click();await t.locator('.endpoint-summary').first().click();await expect(t.getByRole('button',{name:'发送请求',exact:true})).toHaveCount(0);record('教师业务文档仅阅读')
 await t.getByRole('button',{name:'退出登录',exact:true}).click();await expect(t).toHaveURL(/\/login$/);record('教师退出登录')
 const sc=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});await track(sc);const s=await sc.newPage();await login(s,'DEMO2026001');await expect(s.locator('.detail-list')).toBeVisible();record('学生真实登录及本人空间信息')
 await s.screenshot({path:'../docs/screenshots/student-home.png',fullPage:true});await s.goto('http://localhost:5173/teacher/users');await expect(s).toHaveURL('http://localhost:5173/');record('学生直接修改地址无法进入教师页')
 await s.getByRole('link',{name:'接口地址',exact:true}).click();await s.getByRole('button',{name:'复制地址',exact:true}).first().click();const copied=await s.evaluate(()=>navigator.clipboard.readText());expect(copied).toMatch(/^http:\/\/localhost:8100\/api\/practice\/[a-f0-9]{64}\/ticket$/);record('复制本人完整后端地址')
 await s.getByRole('link',{name:'我的项目数据',exact:true}).click();await expect(s.getByRole('table')).toBeVisible();await expect(s.locator('tbody tr')).not.toHaveCount(1);await s.getByRole('button',{name:'活动列表',exact:true}).click();await expect(s.getByRole('cell',{name:'联调验证活动',exact:true}).first()).toBeVisible();record('学生读取真实抢票数据')
 await s.getByRole('button',{name:'校园报修',exact:true}).click();await expect(s.locator('.identity-bar select option')).not.toHaveCount(1);await s.getByRole('button',{name:'工单列表',exact:true}).click();await expect(s.getByRole('cell',{name:'课堂联调：设备检查',exact:true}).first()).toBeVisible();await s.screenshot({path:'../docs/screenshots/repair-data.png',fullPage:true})
 await s.getByRole('row').filter({has:s.getByRole('cell',{name:'课堂联调：设备检查',exact:true})}).first().getByRole('button',{name:'查看详情'}).click();await expect(s.getByRole('dialog')).toBeVisible();await s.getByRole('button',{name:'处理记录',exact:true}).click();await expect(s.getByRole('dialog').getByText('已检查设备供电，准备试运行。',{exact:false})).toBeVisible();await s.getByRole('button',{name:'工单图片',exact:true}).click();await s.getByRole('button',{name:'预览',exact:true}).first().click();await expect(s.getByAltText('工单图片预览')).toBeVisible();const downloadPromise=s.waitForEvent('download');await s.getByRole('button',{name:'下载',exact:true}).first().click();const download=await downloadPromise;expect(download.suggestedFilename()).toBeTruthy();await s.getByRole('button',{name:'工单评价',exact:true}).click();await expect(s.getByRole('dialog').getByText('处理及时，谢谢。',{exact:true})).toBeVisible();await s.getByRole('button',{name:'关闭',exact:true}).click();record('维修详情、处理记录、图片预览下载和评价')
 // 在真实后端上验证文档请求和浏览器冷却；未拦截或模拟任何后端响应。
 await s.getByRole('navigation').getByRole('link',{name:'接口文档',exact:true}).click();await expect(s.getByRole('button',{name:'系统管理',exact:true})).toHaveCount(0);await s.getByLabel('搜索接口').fill('查询抢票活动详情');await s.locator('.endpoint-summary').click();await s.getByRole('button',{name:'发送请求',exact:true}).click();await expect(s.getByRole('alert')).toContainText('请填写');expect(await s.evaluate(()=>localStorage.getItem('practice:DEMO2026001:docs:deadline'))).toBeNull();record('本地参数校验失败不启动十秒计时')
 await s.getByLabel('搜索接口').fill('查询抢票活动列表');await s.locator('.endpoint-summary').click();await s.getByRole('button',{name:'发送请求',exact:true}).click();await expect(s.locator('.response-meta')).toContainText('HTTP 200');await expect(s.locator('.cooldown-banner')).toBeVisible();await s.screenshot({path:'../docs/screenshots/docs-response.png',fullPage:true});record('文档真实请求、实际地址、耗时和响应展示')
 await s.reload();await expect(s.locator('.cooldown-banner')).toBeVisible();record('文档十秒冷却刷新保留')
 await s.getByLabel('搜索接口').fill('查询抢票模拟用户列表');await s.locator('.endpoint-summary').click();await expect(s.locator('.endpoint-body .toolbar button').first()).toBeDisabled();record('切换接口共用十秒计时')
 await s.getByRole('link',{name:'我的项目数据',exact:true}).click();await s.getByRole('button',{name:'刷新数据',exact:true}).click();await expect(s.locator('.table-wrap tbody')).toContainText('模拟');record('只读数据刷新不受文档冷却影响')
 await s.setViewportSize({width:390,height:844});await noOverflow(s,'手机数据页无横向溢出');await s.getByRole('link',{name:'接口地址',exact:true}).click();await noOverflow(s,'手机地址页可读');await s.screenshot({path:'../docs/screenshots/addresses-mobile.png',fullPage:true})
 // 第二名学生用于重置验收，第一名保留可展示的业务数据。
 await s.getByRole('button',{name:'退出登录',exact:true}).click();await login(s,'DEMO2026002');await s.getByRole('link',{name:'数据重置',exact:true}).click();await s.getByRole('button',{name:'重置所选项目',exact:true}).click();await sc.setOffline(true);await s.getByRole('button',{name:'确认重置',exact:true}).click();await expect(s.getByRole('dialog').getByRole('alert')).toBeVisible();expect(await s.evaluate(()=>localStorage.getItem('practice:DEMO2026002:reset:deadline'))).toBeNull();record('网络失败的重置不启动五分钟冷却');await sc.setOffline(false);await s.getByRole('button',{name:'确认重置',exact:true}).click();await expect(s.getByRole('status').filter({hasText:'重置成功'})).toBeVisible();await expect(s.getByRole('button',{name:/请在.*后再次重置/})).toBeDisabled();record('真实重置成功才启动五分钟冷却');await s.screenshot({path:'../docs/screenshots/reset-mobile.png',fullPage:true});await noOverflow(s,'手机重置页无横向溢出')
 const deadline=await s.evaluate(()=>localStorage.getItem('practice:DEMO2026002:reset:deadline'));await s.reload();await expect(s.getByRole('button',{name:/请在.*后再次重置/})).toBeDisabled();expect(await s.evaluate(()=>localStorage.getItem('practice:DEMO2026002:reset:deadline'))).toBe(deadline);record('五分钟冷却刷新不清零')
 const tab=await sc.newPage();await tab.goto('http://localhost:5173/login');await tab.evaluate(v=>sessionStorage.setItem('vue-practice-session',v),await s.evaluate(()=>sessionStorage.getItem('vue-practice-session')));await tab.goto('http://localhost:5173/reset');await expect(tab.getByRole('button',{name:/请在.*后再次重置/})).toBeDisabled();record('同一学号跨标签页共享重置截止时间')
 await s.getByRole('button',{name:'退出登录',exact:true}).click();await login(s,'DEMO2026002');await s.getByRole('link',{name:'数据重置',exact:true}).click();await expect(s.getByRole('button',{name:/请在.*后再次重置/})).toBeDisabled();record('退出再登录保留本人冷却')
 await s.getByRole('button',{name:'退出登录',exact:true}).click();await login(s,'DEMO2026001');await s.getByRole('link',{name:'数据重置',exact:true}).click();await expect(s.getByRole('button',{name:'重置所选项目',exact:true})).toBeEnabled();record('不同学号冷却隔离')
 // 用浏览器时钟模拟截止时间到达，验证不依赖累计减一。
 await tab.clock.install();await tab.clock.fastForward(301000);await expect(tab.getByRole('button',{name:'重置所选项目',exact:true})).toBeEnabled();record('五分钟截止后按钮自动恢复（浏览器时钟）')
 await s.getByRole('navigation').getByRole('link',{name:'接口文档',exact:true}).click();await s.getByLabel('搜索接口').fill('查询抢票模拟用户列表');await s.locator('.endpoint-summary').click();await noOverflow(s,'手机接口文档无横向溢出');await s.screenshot({path:'../docs/screenshots/docs-mobile.png',fullPage:true})
 expect(errors).toEqual([]);record('浏览器无未处理脚本错误')
 const text=await s.locator('body').innerText();expect(text).not.toMatch(/AI生成|人工智能生成|提示词|由模型生成/);record('产品页面无工具宣传文案')
}catch(e){console.error(e);process.exitCode=1}finally{writeFileSync('../docs/browser-results.json',JSON.stringify({date:new Date().toISOString(),checks,errors,network},null,2));await browser.close()}
