import {chromium,expect} from '@playwright/test'
import {writeFileSync} from 'node:fs'
const browser=await chromium.launch({executablePath:'/opt/google/chrome/chrome',headless:true,args:['--no-sandbox']})
const checks=[],errors=[];const context=await browser.newContext();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept())
function done(name){checks.push({name,passed:true});console.log('通过',name)}
try{
 await page.goto('http://localhost:5173/login');await page.getByLabel('系统用户编号',{exact:true}).fill('DEMO2026001');await page.getByLabel('登录密码').fill('123456');await page.getByRole('button',{name:'登录平台'}).click();await expect(page).toHaveURL('http://localhost:5173/')
 await page.getByRole('navigation').getByRole('link',{name:'接口文档',exact:true}).click();await page.getByLabel('搜索接口').fill('查询抢票活动详情');await page.locator('.endpoint-summary').click();await page.getByLabel('activityId',{exact:true}).fill('999999999');await page.getByRole('button',{name:'发送请求',exact:true}).click();await expect(page.locator('.response-meta')).toContainText('HTTP 404');await expect(page.locator('.cooldown-banner')).toBeVisible();done('真实404错误同样启动文档十秒计时')
 await page.clock.install();await page.clock.fastForward(11000);await expect(page.getByRole('button',{name:'发送请求',exact:true})).toBeEnabled();done('文档十秒到期自动恢复')
 await page.getByRole('button',{name:'校园报修',exact:true}).click();await page.getByLabel('搜索接口').fill('上传故障或维修图片');await page.locator('.endpoint-summary').click();const session=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('vue-practice-session')));const users=await (await fetch(`http://localhost:8100/api/practice/${session.apiAccessCode}/repair/users`)).json();const reporter=users.data.find(x=>x.role==='REPORTER'&&x.status===1)
 await page.getByLabel('operatorId',{exact:true}).fill(String(reporter.id));await page.getByLabel('imageType',{exact:true}).fill('1');await page.getByLabel('file',{exact:true}).setInputFiles('../reference/spdn_13_Emarket/images/red-tablet.png');await page.getByRole('button',{name:'发送请求',exact:true}).click();await expect(page.locator('.response-meta')).toContainText('HTTP 200');done('文档multipart表单真实上传图片')
 const json=JSON.parse(await page.locator('.response pre').innerText());const id=json.data.id;await page.clock.fastForward(11000);await page.getByLabel('搜索接口').fill('预览图片');await page.locator('.endpoint-summary').click();await page.getByLabel('imageId',{exact:true}).fill(String(id));await page.getByRole('button',{name:'发送请求',exact:true}).click();await expect(page.getByAltText('接口返回图片')).toBeVisible();done('文档正确识别二进制图片响应')
 await page.clock.fastForward(11000);await page.getByLabel('imageId',{exact:true}).fill('999999999');await page.getByRole('button',{name:'发送请求',exact:true}).click();await expect(page.locator('.response-meta')).toContainText('HTTP 404');await expect(page.locator('.response pre')).toContainText('message');done('图片错误JSON可读且未误当作图片')
 await page.clock.fastForward(11000);await page.getByLabel('搜索接口').fill('创建维修模拟用户');await page.locator('.endpoint-summary').click();const admin=users.data.find(x=>x.role==='ADMIN'&&x.status===1);await page.getByLabel('JSON请求内容').fill(JSON.stringify({operatorId:admin.id,userNo:'UI_TEST_'+Date.now(),realName:'文档请求验证',role:'REPORTER',phone:'13800000000',status:1}));await page.getByRole('button',{name:'发送请求',exact:true}).click();await expect(page.locator('.response-meta')).toContainText('HTTP 200');const created=JSON.parse(await page.locator('.response pre').innerText()).data;done('文档JSON请求真实创建及显示响应')
 await page.clock.fastForward(11000);await page.getByLabel('搜索接口').fill('删除维修模拟用户');await page.locator('.endpoint-summary').click();await page.getByLabel('userId',{exact:true}).fill(String(created.id));await page.getByLabel('operatorId',{exact:true}).fill(String(admin.id));await page.getByRole('button',{name:'发送请求',exact:true}).click();await expect(page.locator('.response-meta')).toContainText('HTTP 200');done('文档危险操作确认及真实删除')
 // 修改的仅为测试浏览器中缓存的过期访问码，验证系统会话与实训鉴权错误分开。
 await page.evaluate(()=>{const s=JSON.parse(sessionStorage.getItem('vue-practice-session'));s.apiAccessCode='a'.repeat(64);sessionStorage.setItem('vue-practice-session',JSON.stringify(s))});await page.goto('http://localhost:5173/data');await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('.toprole')).toContainText('学生');expect(await page.evaluate(()=>!!JSON.parse(sessionStorage.getItem('vue-practice-session'))?.token)).toBeTruthy();done('实训401不会清理系统登录')
 await page.evaluate(code=>{const s=JSON.parse(sessionStorage.getItem('vue-practice-session'));s.apiAccessCode=code;s.token='b'.repeat(64);sessionStorage.setItem('vue-practice-session',JSON.stringify(s))},session.apiAccessCode);await page.goto('http://localhost:5173/');await expect(page).toHaveURL(/\/login$/);await expect(page.getByRole('alert')).toContainText('登录已失效');done('系统401清理登录并提示重新登录')
 expect(errors).toEqual([])
}catch(e){console.error(e);process.exitCode=1}finally{writeFileSync('../docs/edge-browser-results.json',JSON.stringify({checks,errors,date:new Date().toISOString()},null,2));await browser.close()}
